-- CREATE DATABASE FOR BÀI 1
CREATE DATABASE QuanLyNhanVienKD_DB;
GO
USE QuanLyNhanVienKD_DB;
GO

-- 1. BẢNG NHÂN VIÊN
CREATE TABLE NhanVien (
    MaNV VARCHAR(20) NOT NULL PRIMARY KEY,
    TenNV NVARCHAR(120) NOT NULL,
    DiaChi NVARCHAR(250) NULL,
    LoaiNV NVARCHAR(30) NOT NULL DEFAULT N'Thường' CHECK (LoaiNV IN (N'Thường', N'Kinh doanh'))
);

-- 2. BẢNG QUÁ TRÌNH TĂNG LƯƠNG
CREATE TABLE QuaTrinhTangLuong (
    IDTangLuong INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    MaNV VARCHAR(20) NOT NULL,
    NgayHieuLuc DATE NOT NULL,
    LuongMoi DECIMAL(18,2) NOT NULL CHECK (LuongMoi > 0),
    CONSTRAINT FK_TangLuong_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE,
    CONSTRAINT UQ_NV_NgayHieuLuc UNIQUE (MaNV, NgayHieuLuc)
);

-- 3. BẢNG NHÂN VIÊN KINH DOANH
CREATE TABLE NhanVienKinhDoanh (
    MaNV VARCHAR(20) NOT NULL PRIMARY KEY,
    CapDoKD NVARCHAR(30) NOT NULL CHECK (CapDoKD IN (N'Lâu năm', N'Tập sự')),
    MaNVHuongDan VARCHAR(20) NULL, -- NV Tập sự do 0..1 NV Lâu năm hướng dẫn
    CONSTRAINT FK_NVKD_NhanVien FOREIGN KEY (MaNV) REFERENCES NhanVien(MaNV) ON DELETE CASCADE,
    CONSTRAINT FK_NVKD_HuongDan FOREIGN KEY (MaNVHuongDan) REFERENCES NhanVienKinhDoanh(MaNV)
);

-- 4. BẢNG ĐƠN HÀNG
CREATE TABLE DonHang (
    SoDOH VARCHAR(30) NOT NULL PRIMARY KEY,
    KhachHang NVARCHAR(150) NOT NULL,
    TriGia DECIMAL(18,2) NOT NULL DEFAULT 0 CHECK (TriGia >= 0)
);

-- 5. BẢNG THƯƠNG LƯỢNG (Lớp liên kết)
CREATE TABLE ThuongLuong (
    MaNV VARCHAR(20) NOT NULL,
    SoDOH VARCHAR(30) NOT NULL,
    HoaHong DECIMAL(18,2) NOT NULL DEFAULT 0 CHECK (HoaHong >= 0),
    PRIMARY KEY (MaNV, SoDOH),
    CONSTRAINT FK_ThuongLuong_NVKD FOREIGN KEY (MaNV) REFERENCES NhanVienKinhDoanh(MaNV),
    CONSTRAINT FK_ThuongLuong_DonHang FOREIGN KEY (SoDOH) REFERENCES DonHang(SoDOH) ON DELETE CASCADE
);